[build]
# Perintah build untuk Next.js
command = "next build"
# BARIS KRUSIAL: Memberi tahu Netlify bahwa output statis ada di folder 'out'.
publish = "out"

[[plugins]]
# Plugin resmi Netlify untuk menangani routing Next.js.
package = "@netlify/plugin-nextjs"