[build]

#Next.js build command
command = "next build"

[[plugins]]

#The official Netlify plugin to correctly handle Next.js routing,
#serverless functions, and asset optimization.
package = "@netlify/plugin-nextjs"